# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/yukinoroh/Programmes/Unreal5.8.2

TARGETS = \
	SpaceShooter-Android-DebugGame  \
	SpaceShooter-Android-Development  \
	SpaceShooter-Android-Shipping  \
	SpaceShooter-Linux-DebugGame  \
	SpaceShooter-Linux-Development  \
	SpaceShooter-Linux-Shipping  \
	SpaceShooter-LinuxArm64-DebugGame  \
	SpaceShooter-LinuxArm64-Development  \
	SpaceShooter-LinuxArm64-Shipping  \
	SpaceShooter \
	SpaceShooterEditor-Linux-DebugGame  \
	SpaceShooterEditor-Linux-Development  \
	SpaceShooterEditor \
	ChaosTestHarness \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend SpaceShooterEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug SpaceShooterEditor-Linux-Debug


SpaceShooter-Android-DebugGame:
	 $(BUILD) SpaceShooter Android DebugGame  -Project="/home/yukinoroh/Documents/université/8PRO135 - Programmation avec des moteurs de jeu/TP1/SpaceShooter/SpaceShooter.uproject" $(ARGS)

SpaceShooter-Android-Development:
	 $(BUILD) SpaceShooter Android Development  -Project="/home/yukinoroh/Documents/université/8PRO135 - Programmation avec des moteurs de jeu/TP1/SpaceShooter/SpaceShooter.uproject" $(ARGS)

SpaceShooter-Android-Shipping:
	 $(BUILD) SpaceShooter Android Shipping  -Project="/home/yukinoroh/Documents/université/8PRO135 - Programmation avec des moteurs de jeu/TP1/SpaceShooter/SpaceShooter.uproject" $(ARGS)

SpaceShooter-Linux-DebugGame:
	 $(BUILD) SpaceShooter Linux DebugGame  -Project="/home/yukinoroh/Documents/université/8PRO135 - Programmation avec des moteurs de jeu/TP1/SpaceShooter/SpaceShooter.uproject" $(ARGS)

SpaceShooter-Linux-Development:
	 $(BUILD) SpaceShooter Linux Development  -Project="/home/yukinoroh/Documents/université/8PRO135 - Programmation avec des moteurs de jeu/TP1/SpaceShooter/SpaceShooter.uproject" $(ARGS)

SpaceShooter-Linux-Shipping:
	 $(BUILD) SpaceShooter Linux Shipping  -Project="/home/yukinoroh/Documents/université/8PRO135 - Programmation avec des moteurs de jeu/TP1/SpaceShooter/SpaceShooter.uproject" $(ARGS)

SpaceShooter-LinuxArm64-DebugGame:
	 $(BUILD) SpaceShooter LinuxArm64 DebugGame  -Project="/home/yukinoroh/Documents/université/8PRO135 - Programmation avec des moteurs de jeu/TP1/SpaceShooter/SpaceShooter.uproject" $(ARGS)

SpaceShooter-LinuxArm64-Development:
	 $(BUILD) SpaceShooter LinuxArm64 Development  -Project="/home/yukinoroh/Documents/université/8PRO135 - Programmation avec des moteurs de jeu/TP1/SpaceShooter/SpaceShooter.uproject" $(ARGS)

SpaceShooter-LinuxArm64-Shipping:
	 $(BUILD) SpaceShooter LinuxArm64 Shipping  -Project="/home/yukinoroh/Documents/université/8PRO135 - Programmation avec des moteurs de jeu/TP1/SpaceShooter/SpaceShooter.uproject" $(ARGS)

SpaceShooter: SpaceShooter-Linux-Development

SpaceShooterEditor-Linux-DebugGame:
	 $(BUILD) SpaceShooterEditor Linux DebugGame  -Project="/home/yukinoroh/Documents/université/8PRO135 - Programmation avec des moteurs de jeu/TP1/SpaceShooter/SpaceShooter.uproject" $(ARGS)

SpaceShooterEditor-Linux-Development:
	 $(BUILD) SpaceShooterEditor Linux Development  -Project="/home/yukinoroh/Documents/université/8PRO135 - Programmation avec des moteurs de jeu/TP1/SpaceShooter/SpaceShooter.uproject" $(ARGS)

SpaceShooterEditor: SpaceShooterEditor-Linux-Development

ChaosTestHarness: ChaosTestHarness-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/yukinoroh/Documents/université/8PRO135 - Programmation avec des moteurs de jeu/TP1/SpaceShooter/SpaceShooter.uproject" -Game 

.PHONY: $(TARGETS)
